### PR TITLE
Update variables-deploy.md

### PR DESCRIPTION
**Pull request by luanalves**
configure variable to deploy from configure redis preload keys

## Purpose of this pull request

This pull request (PR) ...

## Affected pages

- ...

## Links to Commerce code

- ...

### CODE REVIEW

**Comment by hguthrie** [comment]
We have an internal PR waiting for final approval that addresses this. I will keep this PR open until the technical approval has been granted and the PR is approved and merged.

**Comment by hguthrie** [comment]
@luanalves  One question on your usage, do you also specify a REDIS_BACKEND model or use the default?

**Comment by luanalves** [comment]
> @luanalves One question on your usage, do you also specify a REDIS_BACKEND model or use the default?

In this situation I don't test, but in all systems that I working use REDIS_BACKEND model

**Comment by hguthrie** [comment]
Thank you for your contribution. This was already underway, but your interest sped up the process. Closing this PR since the internal update has been merged. It should go live soon.

**Comment by luanalves** [comment]
> Thank you for your contribution. This was already underway, but your interest sped up the process. Closing this PR since the internal update has been merged. It should go live soon.

thank you

**Pull request closed without merging**
